### ISSUE TITLE
receiver data in layers_sscig.jl is NaN when space_order=4

### ISSUE THREAD

**Issue by br92sil** [slimgroup/ImageGather.jl#4]
Hi @mloubout,

When I set `space_order=4` in `opt = Options(space_order=4, sum_padding=true)`, I am getting
![image](https://user-images.githubusercontent.com/118133556/201542432-e41c2f97-b410-4811-b851-3b4cfbe8adcf.png)

This doesn't happen with other values of `space_order` (e.g. 6, 8, 10 and 12). Any idea of what is going on? This is for `layers_sscig.jl`.

Thanks.

**Comment by mloubout** [comment]
It probably accesses out of bound values with the offset I'll double check. Thanks
